---
title: "ddeocampo-project-1"
author: "Diane DeOcampo"
date: "9/21/2019"
output: html_document
---

# Project 1
any libraries need to be imported
```{r setup}
library(readr)
library(stringr)
library(plyr)
```

#### Read from txt file and import
```{r import}
importtxt <- read_lines("tournamentinfo.txt", skip=4)
```

#### Create empty data frame
```{r dataframe}
playerbase <- data.frame(PairNum=integer(),
                      PlayerName=character(),
                      PlayerState=character(),
                      TotalPoints=integer(),
                      PlayerPreRating=integer())
```

#### read, parse, load into df
```{r parse}
pair_num <- unlist(str_extract(unlist(str_extract_all(importtxt, pattern = "[:digit:]{1,}[:blank:](?=\\|)")), pattern = "[:digit:]"))

player_names <- unlist(str_extract(unlist(str_extract_all(importtxt, pattern = "(?<=\\|)[:space:][:alpha:]{1,}[:space:][:alpha:]{1,}[:space:][:alpha:]{0,}[:space:]{1,}(?=\\|)")), pattern = "[:alpha:]{1,}[:space:][:alpha:]{1,}([:blank:][:alpha:]{1,})?"))

player_state <- unlist(str_extract(unlist(str_extract_all(importtxt, pattern = "[:space:][:upper:]{2}[:blank:](?=\\|)")), pattern = "[:alpha:]{2}"))

total_points <- unlist(str_extract_all(importtxt, pattern = "[:digit:]\\.[:digit:]"))

player_prerating <- unlist(str_extract(unlist(str_extract_all(importtxt, pattern = "R\\:[:blank:][:digit:]{1,4}")), pattern = "[:digit:]{1,4}"))

playerbase <- data.frame(pair_num,
                         player_names,
                         player_state,
                         total_points,
                         player_prerating)
```

#### get player opponents
```{r opponentbase}
tmp <- str_extract_all(importtxt, pattern = "(?<=\\|)(W|D|L)[:blank:]+[:digit:]+(?=\\|)")
tmp <- tmp[lapply(tmp,length)>0]
opponent_num <- str_extract_all(as.character(tmp), pattern = "[:digit:]+")

opponentbase <- list(pair_num,opponent_num)

```

#### 
```{r testing}
oppo_played <- playerbase[unlist(opponentbase[[2]][1]),]
oppo_prerankings <- oppo_played$player_prerating
avg_oppopreranking <- mean(oppo_prerankings[!is.na(oppo_prerankings)])

```

```{r testing 2}
opo_tmp <- unlist(str_extract_all(importtxt, pattern ="(?<=\\|)[:blank:][:alpha:]{1,}[[:blank:](([:alpha:]*){1,}|([:alpha:]*\\-[:alpha:]*){1,}]*(?=\\|)"))

player_names <- unlist(str_extract(opo_tmp, pattern = "[:alpha:]{1,}[:blank:]([:alpha:]+)"))
player_names

```

#### write to csv
write.csv(healthstudy,'healthstudy2.csv')